Optimize Keycloak Dockerfile for Efficiency and Clarity
Grouped related commands into single RUN steps to reduce image layers and streamline the build process.
Added comprehensive comments to each section for better understanding and maintainability.
Implemented cache cleanup with dnf clean all after package installations to minimize the resulting image size.
Consolidated port exposure commands into a single EXPOSE directive for ports 8080 and 8443.
This commit aims to enhance the Docker image build process, making the Dockerfile more efficient and readable.

diff --git a/quarkus/container/Dockerfile b/quarkus/container/Dockerfile
--- a/quarkus/container/Dockerfile
+++ b/quarkus/container/Dockerfile
@@ -1,36 +1,34 @@
+# Use Red Hat's UBI (Universal Base Image) as a build stage named 'ubi-micro-build'
 FROM registry.access.redhat.com/ubi9 AS ubi-micro-build
 
+# Set environment variable for Keycloak version and download link
 ENV KEYCLOAK_VERSION 999.0.0-SNAPSHOT
 ARG KEYCLOAK_DIST=https://github.com/keycloak/keycloak/releases/download/$KEYCLOAK_VERSION/keycloak-$KEYCLOAK_VERSION.tar.gz
 
-RUN dnf install -y tar gzip
+# Install necessary packages, add and unpack Keycloak, then clean up in one layer
+RUN dnf install -y tar gzip && \
+    ADD $KEYCLOAK_DIST /tmp/keycloak/ && \
+    (cd /tmp/keycloak && tar -xvf /tmp/keycloak/keycloak-*.tar.gz && rm /tmp/keycloak/keycloak-*.tar.gz) || true && \
+    mv /tmp/keycloak/keycloak-* /opt/keycloak && \
+    mkdir -p /opt/keycloak/data && \
+    chmod -R g+rwX /opt/keycloak && \
+    dnf clean all
 
-ADD $KEYCLOAK_DIST /tmp/keycloak/
-
-# The next step makes it uniform for local development and upstream built.
-# If it is a local tar archive then it is unpacked, if from remote is just downloaded.
-RUN (cd /tmp/keycloak && \
-    tar -xvf /tmp/keycloak/keycloak-*.tar.gz && \
-    rm /tmp/keycloak/keycloak-*.tar.gz) || true
-
-RUN mv /tmp/keycloak/keycloak-* /opt/keycloak && mkdir -p /opt/keycloak/data
-RUN chmod -R g+rwX /opt/keycloak
-
+# Add the UBI null script and execute it in one layer
 ADD ubi-null.sh /tmp/
 RUN bash /tmp/ubi-null.sh java-17-openjdk-headless glibc-langpack-en findutils
 
+# Use Red Hat's UBI Micro as the final base image
 FROM registry.access.redhat.com/ubi9-micro
 ENV LANG en_US.UTF-8
 
 COPY --from=ubi-micro-build /tmp/null/rootfs/ /
 COPY --from=ubi-micro-build --chown=1000:0 /opt/keycloak /opt/keycloak
 
+# Add keycloak user and group in one layer
 RUN echo "keycloak:x:0:root" >> /etc/group && \
     echo "keycloak:x:1000:0:keycloak user:/opt/keycloak:/sbin/nologin" >> /etc/passwd
 
 USER 1000
-
-EXPOSE 8080
-EXPOSE 8443
-
+EXPOSE 8080 8443
 ENTRYPOINT [ "/opt/keycloak/bin/kc.sh" ]
