make sure the `index.ts` file doesn't change
to ensure backwards compatibility

Signed-off-by: Erik Jan de Wit <erikjan.dewit@gmail.com>

diff --git a/js/.husky/pre-commit b/js/.husky/pre-commit
--- a/js/.husky/pre-commit
+++ b/js/.husky/pre-commit
@@ -28,5 +28,11 @@ pnpm install --reporter=silent || {
   exit 0;
 }
 
+if git diff --name-only --cached | grep 'index.ts$'
+then
+  echo "pre-commit: Aborting you can't change the index.ts file"
+  exit 1
+fi
+
 # Run lint-staged.
 pnpm exec lint-staged
